[package]
name = "snake-cod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cod = { version = "3", features = ["input"] }
device_query = "1.1.1"
rand = "0.8.5"
